### ISSUE TITLE
Temperature settings

### ISSUE THREAD

**Issue by indieflow** [repetier/Repetier-Host-Mac#1]
Wow, thank you very much, this is a massive step forward for Mac users like myself!

I've been running this host all day with hardly any problems!

I have however noticed a few minor problems.
1. After setting default temperatures for extruder and heat bed in printer settings they are still set to 170 extruder and 55 heat bed in the print panel!
2. After the setting "printer has dump area" has been deselected and the host software is restarted the setting is defaulted back to the printer has dump area.
3. At the end of a print job, the temperatures drop on the extruder and heat bed (they turn off as expected), though they are still indicated as on within the print panel. They then have to be turned off and then back on again to heat back up.

**Comment by repetier** [comment]
Thanks for the feedback. I will fix the problems for the next update. I have also fixed the sd management, which has in version 0.10 quite some mistakes.

**Comment by repetier** [comment]
Point 1. and 2. are fixed in version 0.11. Forget to correct point 3. Will add that in the next update.

**Comment by indieflow** [comment]
Champion, I'll get testing!

**Comment by repetier** [comment]
Fixed in version 0.12.
