### ISSUE TITLE
Feature Request: Estimated Printing Duration

### ISSUE THREAD

**Issue by lcis** [repetier/Repetier-Host-Mac#12]
It would be nice to get an estimated printing duration before starting the printing-job.

**Comment by repetier** [comment]
Well, I could add the estimated print duration in the g-code preview. I could show the time needed when printed with full speed not counting time for acceleration/decelleration. So it would be a lower limit, where you need some time depending on your printer configuration.

**Comment by lcis** [comment]
I think an estimated duration +/- 10% or less will do. Compare Pronterface.
The idea is to see, whether the printing duration is too long. Generally I don't print things with long estimated durations.

**Comment by repetier** [comment]
My latest idea is to add a fixed percentage to the computed time, which can be set in the configuration. After some prints you will know how many percent to add with your setting. I think that will give a relive precise estimate.

**Comment by lcis** [comment]
The correction with the fixed percentage will be great. The computed time is ok for the first step.

**Comment by repetier** [comment]
Ok, the github version now contains print time preview with adjustable added percentage. Also used this to imprvoe the ETA live printing time. Binaries will follow when all fetarures planned are included.

**Comment by lcis** [comment]
Thank you for the feature.
Analyze-Error in RHPrintjob.m -> Suggestion for line 49:

```
   - self.ana = [[GCodeAnalyzer alloc] init];
   + ana = [[GCodeAnalyzer alloc] init];
```

Product->Run  ok.
Suggestion for improvement: printing format in hours and minutes:
GCodeView->line 718

```
    - txt = [NSString stringWithFormat:@"%@ Printing time:%d min",txt,tm];
    + txt = [NSString stringWithFormat:@"%@ Printing time:%2dh:%02dm",txt,tm/60,tm%60];
```

**Comment by repetier** [comment]
What's wrong with self.ana? ana is a property which stores it's value in self->ana and it is working on my machine as expected.

I have added the conversion into hours for the preview.

**Comment by lcis** [comment]
Running Product->Analyze I got an error (Potential leak of an object on line 49).
I didn't investigate why, but changing as described above (without self.) the error disappeared.

**Comment by repetier** [comment]
Ok, found the reason. The property did add a retain so I had to do a autorelease like this:

self.ana = [[[GCodeAnalyzer alloc] init] autorelease];

then no error is reported.

**Comment by lcis** [comment]
ok, generally I avoid autorelease, but sometime there is no alternatives, is up to you.

Edit:
I forgot to mention that using "ana = [[GCodeAnalyzer alloc] init];" I also added "[ana release];" in -(void)dealloc.
