### ISSUE TITLE
connectButton Label

### ISSUE THREAD

**Issue by lcis** [repetier/Repetier-Host-Mac#13]
Another simple solution:

RHAppDelegate.m

line 40

```
  + #define CONNECT_LABEL @"Connect    "
```

line 102 

```
    +    [connectButton setLabel:CONNECT_LABEL];
```

line 328

```
    -    [connectButton setLabel:@"Connect"];
    +    [connectButton setLabel:CONNECT_LABEL];
```

**Comment by repetier** [comment]
I took this option. Like the names more and the result is at least better. Still a tiny difference, but not so much as before.

**Comment by lcis** [comment]
Ok. The tiny difference depends on the proportional font used. With a fixed-width font there wouldn't be any difference.
