### ISSUE TITLE
ETA

### ISSUE THREAD

**Issue by napanorton** [repetier/Repetier-Host-Mac#19]
Any clues as to why the ETA is so off? I Estimation was 15 min and the actual was more like 40. Not really a problem, but it is nice to know when to check back on the print.

Thanks, David

**Comment by repetier** [comment]
The ETA is based on the given feedrate but doesn't consider acceleration. If you have slow acceleration, many small moves, low jerk the quantity of acceleration can become considerable high. Especially with infills like hexagon infill. You can scale the given eta in the printer settings. There is a field to add x percent to computed time. Looks like your settings need much higher additions then the default ones. At least if every print has so much deviation.
