### ISSUE TITLE
Please add more (higher) baud rates

### ISSUE THREAD

**Issue by MaikStohn** [repetier/Repetier-Host-Mac#24]
I did some experiments today (using OSX10.8 and ATmega16U2 powered USB to serial converter like on Arduino2560-R3) to find out the maximum possible baud rates:

In "PrintSettingController" I added

``` c
... ,@"500000",@"1000000",@"1500000",@"2000000",nil]];
```

to the end of the possible baud rate list.

  500000 ==> no problems

1000000 ==> no problems

1500000 ==> no problems   <== this is what I prefer for printing now

2000000 ==> ok, but got a few transmission errors during print (caused by RepRap firmware which can not receive so fast)

NOTE: This was tested on MacOSX10.8 + ATmega16U2 as USB to serial converter. But I think FTDI based converters should be able to do the same.

Thanks,

Maik

**Comment by repetier** [comment]
Ok, added the baud rates for the next release. 

You know that the latency between 2 USB packages has more influence then the baud rate? I know where to change the latency for windows, but not for the mac. Have you any idea where I can set it?

**Comment by MaikStohn** [comment]
You can set the "IO Serial Stream DATA LATency" for the Apple serial port driver (and derived ones) using the following ioctl:

``` c
#include <sys/ioss.h>

unsigned long microseconds = 1000;
ioctl(fdCOMPort, IOSSDATALAT, &microseconds);
```

However the sender also should have a very small latency. For FTDI based devices you can use MProg to change the FTDI internal parameter. For 8U2/16U2 based devices you need to tweak their firmware a bit.
But fiddeling with MProg / changing the 16U2 firmware can cause some trouble I don't think it's easy for the average user to do it properly. Worst case they manage to setup something unresponsive and are unable to recover. 

Maik

**Comment by repetier** [comment]
Implemented.
