### ISSUE TITLE
Setting for "Start" G-Code Sequence in Preferences

### ISSUE THREAD

**Issue by dognotdog** [repetier/Repetier-Host-Mac#36]
I would particularly like to insert an M80 command at the beginning of the gcode, automatically, as having to hand edit things is a bit tedious and error prone. As it is, the temperature settings come first, but without power, the print will never start.

**Comment by repetier** [comment]
Please check the g-code tab. There you can also select start code. This is run before any slicer output is run. Hit save button to save it permanently with your printer preferences.

**Comment by dognotdog** [comment]
Alright, so the following typical lines:

> M107
> M190 S60 ; wait for bed temperature to be reached
> M104 S192 ; set temperature

are generated by slic3r? That the g-code in the "g-code tab" is saved was also not obvious, thanks for pointing that out!

**Comment by repetier** [comment]
Yes if they apear in the gcode it is from the slicer. All other code settings in gcode are stored with the printer settings.

**Comment by dognotdog** [comment]
Alright, I'll have a word with the slic3r source, then :)
