### ISSUE TITLE
0.55 Mac no longer slices

### ISSUE THREAD

**Issue by i-make-robots** [repetier/Repetier-Host-Mac#37]
Downloaded and installed the update last night. Tried to slice and got warnings about the GUI and outdated trackpad controls. Refuses to slice.  Please advise.

**Comment by repetier** [comment]
What are trackpad controls? What are the warnings? Do you use the builtin slicer or an external one? Which slicer are you talking about? 

Now you can set the slic3r version in the preferences and the default is 0.9.9 which adds some parameter not working with older versions.

**Comment by i-make-robots** [comment]
9:29:51 PM: <Slic3r> 2013-04-06 21:29:51.140 slic3r[30112:407] -_continuousScroll is deprecated for NSScrollWheel. Please use -hasPreciseScrollingDeltas.
  9:29:51 PM: <Slic3r> 2013-04-06 21:29:51.143 slic3r[30112:407] -deviceDeltaX is deprecated for NSScrollWheel. Please use -scrollingDeltaX.
  9:29:51 PM: <Slic3r> 2013-04-06 21:29:51.144 slic3r[30112:407] -deviceDeltaY is deprecated for NSScrollWheel. Please use -scrollingDeltaY.

I'm using 0.9.9 with the settings I had previously set up in earlier versions.

**Comment by repetier** [comment]
I get the same warnings. Ignore them or send a complain to the slic3r author. These are minor warnings from the gui and have nothing to do with the slic3r results.

**Comment by repetier** [comment]
I have an other user with the same problem. Looks like a new error in my slicer handling. Need to investigate further.

**Comment by repetier** [comment]
Fixed in the new version 0.55 (your title was wrong, it was 0.54 with the fault).
