### ISSUE TITLE
Wrong instructions in Configuration.h for USE_GENERIC_THERMISTORTABLE_1

### ISSUE THREAD

**Issue by biocode3D** [repetier/Repetier-Host-Mac#43]
The instructions on the generic thermistor tables is backward.  This is really trivial; but it did cause me some confusion.

If you don't need the generic table, uncomment the following define.
*/
//#define USE_GENERIC_THERMISTORTABLE_1

Should be:
If you need the generic table, uncomment the following define.

**Comment by repetier** [comment]
Absolutely right. How could such an error exist for over a year??? Fixed for version 0.90
