### ISSUE TITLE
repetier allowing HARDWARE  damaging out of bounds moves.

### ISSUE THREAD

**Issue by mrbi11** [repetier/Repetier-Host-Mac#56]
Greetings,

In determining the actual limits of the machine, i tried to print a 140mm circle.
Slic3r aggravated the issue by generating some moves actually outside the envelop.

THIS GENERATED SOME HARMFUL MOVES MY PRINTER WAS BANGING INTO ITSELF WITH GREAT FORCE! 
The rostock did not ignore out of bound moves as it should!

There is actually a simple check. The code appears to have an aborted attempt to check. I am unfamiliar with the # of steps, so please presume these values are adjusted per internal distance values.

For any given move, calculate its final absolute X and Y position (in physical units.)
It needs to calculate a constant value at start up from "printer radius".
If printer radius is set to 140, the
 // the SQUARE of the limit of the cartesian X or Y axis
 AbsLimitSquared = scaled (140)*scaled(140);

The test is simple for cartesian coordinates, using pythagorean formula
TargetAbsX = // calculate final x coordinate 
TargetAbsY = // ditto
If ( ((TargetAbsX_TargetAbsX)+(TargetAbsY_TargetAbsY)) > AbsLimitSquared) {
   // do anything EXCEPT the move, just don't break the hardware!
} else {
   // process move as usual
}

Found commented out complex code for checking bounds in >>motion.cpp<<:
It appears someone tried this but made it too complicated.
# if max_software_endstop_r == true

// TODO - Implement radius checking
// I'm guessing I need the floats to prevent overflow. This is pretty horrible.
// The NaN checking in the delta calculation routine should be enough
//float a = difference[0] \* difference[0] + difference[1] \* difference[1];
//float b = 2 \* (difference[0] \* printer_state.currentPositionSteps[0] + difference[1] \* printer_state.currentPositionSteps[1]);
//float c = printer_state.currentPositionSteps[0] \* printer_state.currentPositionSteps[0] + printer_state.currentPositionSteps[1] \* printer_state.currentPositionSteps[1] - r \* r;
//float disc = b \* b - 4 \* a \* c;
//if (disc >= 0) {
//    float t = (-b + (float)sqrt(disc)) / (2 \* a);
//    printer_state.destinationSteps[0] = (long) printer_state.currentPositionSteps[0] + difference[0] \* t;
//    printer_state.destinationSteps[1] = (long) printer_state.currentPositionSteps[1] + difference[1] \* t;
//}
# endif

(And to the author, yes, this is pretty horrible :-)
(I have only found more complex ways to do simple things when looking back at my own code. :-)

I will be happy to send actual code if someone is going to incorporate it into the system. Id need an explanation about what units the x and y cartesian coordinates are in. From above, it appears
TargetAbsX =  printer_state.destinationSteps[0]
and
TargetAbsY =  printer_state.destinationSteps[1]

By all means correct me if I misread it.

**Comment by pastprimitive** [comment]
Yes, yes this about broke my machine. Moved back to a mac in the house, downloaded Repetier for mac... and thought surely it would at least have limit stops worked out.... 

I'm going to jump on board trying to see if I can fix the problem in the mean time while I wait for an update.  If anyone has already fixed this problem OH please let me know, it would be much appreciated.

**Comment by repetier** [comment]
Hi, sorry to hear something broke. The todays update contains the radius check and some more delta related fixes. New changes are also available over the online configurator.

**Comment by mrbi11** [comment]
We are working to improve the delta safety and accuracy, but currently 
still in testing phase.
(we in the i just volunteered sense, but I am several months into 
development and close)
if you like I can let you know when a beta is available, and details.

peace,
*Bill Kelley
- 512 266 1896
