### ISSUE TITLE
Only seeing 1/4 of 3D print preview

### ISSUE THREAD

**Issue by tonystockert** [repetier/Repetier-Host-Mac#69]
For some reason, I only see 1/4 of my print area (one quadrant) in the live 3D view of the print. I am able to see the preview under the G-Code panel, but when I switch to the Print Panel it doesn't show me all the information.

Attached screenshots as well as the printer settings window. Didn't have this issue with the Windows version at work and all the settings seem to be the same. Also, I have a delta (Rostock).

Thanks.

![screen shot 2015-05-30 at 8 50 04 pm](https://cloud.githubusercontent.com/assets/10445288/7900468/97e6e888-070e-11e5-830a-e0fe91ee66de.png)
![screen shot 2015-05-30 at 8 49 53 pm](https://cloud.githubusercontent.com/assets/10445288/7900469/9dcf7594-070e-11e5-8d78-cbb7d37e7221.png)
![screen shot 2015-05-30 at 8 53 43 pm](https://cloud.githubusercontent.com/assets/10445288/7900473/b5a78184-070e-11e5-983c-81c50202e9b9.png)

**Comment by repetier** [comment]
That is because you said so. See last image where cursor is. X min and y min is 0, so preview clips all moves there just as you said. Enter -160 there and 160 in max and it should show as you expect.
