### ISSUE TITLE
G-Code visualization shows first layer below the grid / other suggestions

### ISSUE THREAD

**Issue by stohn** [repetier/Repetier-Host-Mac#7]
First I want to thank you for this great piece of software. I use it for one week now and can't imagine to go back to anything else I used before :-) Keep up the good work!
# Issue:

When I load a gcode file the first layer is always drawn outside the bounding box (below the grid).
Maybe it has something to do with my small first layer height (0.1mm) or it is a general issue. I think the visualization starts just 1mm below the grid.
The following (abstract) gcode file demonstrates the problem:

G1 Z0.100
G1 X40 Y40
G1 X80 Y40 E2.25604

You can see that the visualization of the object is outside of the bounding box (below the grid).
# Suggestions:
- I like the new G-Code Visualization feature a lot. It would be nice to scroll through the single layers with the mouse (e.g. using shift key + mouse scroll). Now you only can use the slider to step through the layers and the image is not update while moving the slider.
- The feed rate for moving the head manually in print panel is much to slow for me. Either add an option for it or increase it please.
- I seriously miss a button to set origin (usually I move the head before printing and fine tune my z-axis by hand - endstops are just not good enough when printing <= 0.1mm layer height). When done I have to send a G92 to set the origin. A button for this would be nice...

Thanks,

Maik

**Comment by repetier** [comment]
The preview does what it should. From the current height it goes a layer height down. The Layer height used is set in the preferences. Setting this from 0.4 to 0.1 shows it above the grid. I will see if I can come up with a fix for the first layer. In this special case the height could be reduced so it is always above the grid.

Suggestions:
1. Sounds good. I'm already working an a continuous update but currently apple cocoa refuses to redraw during slide. But perhaps I find a solution to convince it.
2. The Setting is Printer settings->behaviour->Travel speed
3. Will search a place for this.
