### ISSUE TITLE
Connect to Repetier Server

### ISSUE THREAD

**Issue by sigxcpu76** [repetier/Repetier-Host-Mac#71]
I wish a single enhancement for this app: connect to Repetier-Server, for remote printing. I know the development is stalled, but except other enhacements in Windows/Linux versions, this will make a big difference for me.

**Comment by repetier** [comment]
Sorry, but that is not gonna happen. That is a very complicated thing taking too long. It will be faster to use the web frontend. We are already working on the slicer for the server, then you can do anything in the web frontend you could do on the host. After that we will even make apps using the frontend inside, also for mac, so it feels again like a native software you can start from mac directly.
