### ISSUE TITLE
USB Driver doesn't detect

### ISSUE THREAD

**Issue by marti1125** [repetier/Repetier-Host-Mac#74]
After install driver USB I don't see in the printer settings the usbconnection
I installed FTDIUSBSerialDriver.kext

<img width="484" alt="captura de pantalla 2018-12-05 a la s 07 16 48" src="https://user-images.githubusercontent.com/223240/49513063-c7a61f00-f85d-11e8-8d9c-a1c3a85d2d8e.png">

following the pdf instructions:

[Repetier-Host Compact settings .pdf](https://github.com/repetier/Repetier-Host-Mac/files/2648745/Repetier-Host.Compact.settings.pdf)

**Comment by repetier** [comment]
You could try rebooting to see if the port appears. Note that you need to connect printer to be able to see it. If running parallels make sure the port is not assigned to windows instead.

If it does not work I'd suggest checking their homepage. Maybe the driver is not compatible with the mac version you have and you need a newer version.
