### ISSUE TITLE
Gcode written to sdcard is missing start and end gcodes

### ISSUE THREAD

**Issue by polygonhell** [repetier/Repetier-Host-Mac#9]
At least as far as I can tell.
I have some end gcode that just moves back to 0,0  and raises the head 10mm and it doesn't seem to run when I upload it to SDCard , and run from there. I do have the add start/end gcode checked when I upload.

**Comment by repetier** [comment]
Yes, without start/end only the pure text in G-Code tab or selected file is uploaded. With the checkboxes you can select the additional code to upload it too.

**Comment by polygonhell** [comment]
Even with the checkboxes set it doesn't seem to add the end gcode.

**Comment by repetier** [comment]
You can see if it is uploaded in the log if you enable send. The last commands send should match your end. I will check the host myself when I get some time to test it.

**Comment by polygonhell** [comment]
OK I just tried that checking the box is appending additional code, but it's not the code from the start/end fragments, I'm uploading the current GCode 

My end code looks like this
G1 X0 Y0
G91
G1 Z10
G90

This is what gets appended - the M107 is the last line from the generated GCode

> 1:45:53 PM: N11394 M107 *11
> 1:45:53 PM: N11396 G0 *5
> 1:45:53 PM: N11397 G0 *4
> 1:45:53 PM: N11398 G0 *11
> 1:45:53 PM: N11399 G0 *10
> 1:45:53 PM: N11400 G0 *13
> 1:45:53 PM: N11401 G0 *12
> 1:45:53 PM: N11402 M29 *62

Thanks

**Comment by repetier** [comment]
Issue is fixed in version 0.16.
